### ISSUE TITLE
epstopdf.cfg no longer read(?)

### ISSUE THREAD

**Issue by herbs** [ho-tex/epstopdf#1]
With the latest update of 2019/11/27 it appears that my TEXMFLOCAL/tex/latex/config/epstopdf.cfg is no longer being read. I have some additional conversions that no longer automatically work there.

**Comment by u-fischer** [comment]
see issue #2

**Comment by davidcarlisle** [comment]
I am re-opening this, there really are two issues  this one, the new `-base` processing only loads `epstopdf-sys.cgf`   and #2 the new `-base` processing doesn't load a dozen extra packages.

For the cfg file, technically just the `epstopdf-sys.cgf` should be enough (it just input `epstopdf-sys.cgf` and `epstopdf.cgf` in succession, but reverting to including the `epstopdf.cgf` is a possibility (but may lead to undefined command errors) or adding a new `epstopdf-base.cgf` file would also be a possibility.

My current preference would be to stick with just `epstopdf-sys.cgf`  but I don't want to close this yet,

**Comment by davidcarlisle** [comment]
As discussed under #2  I have adjusted the base code to always load the cfg, restoring a layer of compatibility. This has gone to ctan just now, so should be in distributions early next week.

Sorry for the inconvenience.
